Init scratch
idisblueflash/Omni-embed-search pull request #7
Opened 2023-10-28 06:43 UTC by vlifeng

scrach files from ground, you can run: 

1. solve deps by: 
yarn 

2. launch a repl server by:
npx shadow-cljs server

3. connect to repl with cider client in IDE:
cider-connect

2023-10-28 15:14 UTC, idisblueflash requested changes

2023-10-28 15:14 UTC, idisblueflash commented on deps.edn
> +  }
@vlifeng 有必要在开始就引入这么多的包吗？还是说，这是Shadow.cljs自己安装的？

2023-10-28 15:14 UTC, idisblueflash commented on deps.edn
> +  ring                           {:mvn/version "1.9.4"}
我在第一次运行REPL的时候遇到了DEPRECATED提醒，这些包是不是需要更新一下？

DEPRECATED: Libs must be qualified, change mount => mount/mount (deps.edn)
DEPRECATED: Libs must be qualified, change nano-id => nano-id/nano-id (deps.edn)
DEPRECATED: Libs must be qualified, change clojure.java-time => clojure.java-time/clojure.java-time (deps.edn)
DEPRECATED: Libs must be qualified, change clj-time => clj-time/clj-time (deps.edn)
DEPRECATED: Libs must be qualified, change datascript => datascript/datascript (deps.edn)
DEPRECATED: Libs must be qualified, change ring => ring/ring (deps.edn)
DEPRECATED: Libs must be qualified, change markdown-to-hiccup => markdown-to-hiccup/markdown-to-hiccup (deps.edn)
DEPRECATED: Libs must be qualified, change instaparse => instaparse/instaparse (deps.edn)
DEPRECATED: Libs must be qualified, change nrepl => nrepl/nrepl (deps.edn)
DEPRECATED: Libs must be qualified, change clj-http => clj-http/clj-http (deps.edn)
DEPRECATED: Libs must be qualified, change ring-middleware-format => ring-middleware-format/ring-middleware-format (deps.edn)
DEPRECATED: Libs must be qualified, change datascript-transit => datascript-transit/datascript-transit (deps.edn)

2023-10-28 15:14 UTC, idisblueflash commented on shadow-cljs.edn
> +
我们是不是应该把:source-paths 放到deps.edn文件里？
因为运行REPL的时候有这个提醒：

```
shadow-cljs - config: /Users/husongtao/Projects/Omni-embed-search/shadow-cljs.edn
shadow-cljs - starting via "clojure"
==============================================================================
WARNING: The configured :source-paths in shadow-cljs.edn were ignored!
         When using :deps they must be configured in deps.edn
==============================================================================
```

2023-10-28 15:34 UTC, idisblueflash commented on deps.edn
> +  ring                           {:mvn/version "1.9.4"}
我尝试创建了一个shadow.cljs demo项目，但未发现deps.edn。我猜测可能是你把常用包都配置进来了。这对新手不太友好。为了更好地学习，我建议简化deps.edn，只保留必要的包，其他的按需添加，这样可以让我清楚知道每个包的用途。

2023-10-28 15:35 UTC, idisblueflash commented on deps.edn
> +  }
我尝试创建了一个shadow.cljs demo项目，但未发现deps.edn。我猜测可能是你把常用包都配置进来了。这对新手不太友好。为了更好地学习，我建议简化deps.edn，只保留必要的包，其他的按需添加，这样可以让我清楚知道每个包的用途。

2023-10-28 15:39 UTC, idisblueflash commented
#1 让我们把PR和Issue关联起来吧！

2023-10-29 02:49 UTC, vlifeng commented on deps.edn
> +  }
shadow.cljs的依赖项可以放在 shadow 的edn 里，也可以放在deps.edn 里

2023-10-29 02:50 UTC, vlifeng commented on deps.edn
> +  }
这里我平时习惯让deps管理依赖，让shadow 管理 build 项和参数

2023-10-29 02:51 UTC, vlifeng commented on shadow-cljs.edn
> +
Done

2023-10-29 11:53 UTC, idisblueflash commented on deps.edn
> +  }
我们是不是应该把ring相关的包也移除？
因为我们准备用pedestal来设计后端（或者你更熟ring，我和你学ring也OK）

前端相关的包比如reitit是不是也可以移除？
因为我们现在还不打算引入前端，我们可以在以后再引入。

2023-10-29 13:39 UTC, vlifeng commented on deps.edn
> +  }
OK, 可以的。

2023-10-29 23:09 UTC, idisblueflash approved these changes

2023-10-30 10:34 UTC, merged